# Generated by Django 6.0.2 on 2026-02-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Company Account'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student Account'),
        ),
    ]
