# Generated by Django 6.0.2 on 2026-03-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Example: 1, 2, or 0 for fresh graduates', verbose_name='Years of Experience'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma separated. Example: English, German', max_length=500, null=True, verbose_name='Spoken Languages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma separated. Example: Python, Django, React', max_length=500, null=True, verbose_name='Technical Skills'),
        ),
    ]
