# Generated by Django 6.0.2 on 2026-03-07 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_company_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.IntegerField(default=0, verbose_name='ATS Match Score (%)'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Minimum years of experience required'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_languages',
            field=models.CharField(blank=True, help_text='Comma separated. Example: English, German', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.CharField(blank=True, help_text='Comma separated. Example: Python, React, SQL', max_length=500, null=True),
        ),
    ]
