# Generated by Django 5.0 on 2026-04-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_link', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('UNDER_REVIEW', 'İnceleniyor'), ('ACCEPTED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('CANCELED', 'İptal Edildi')], default='PENDING', max_length=20)),
                ('match_score', models.FloatField(default=0.0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Örn: Python, Django, SQL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
